version: '3.7'

services:
    adminer:
        image: adminer
        restart: unless-stopped
        ports:
            - '8081:8080'

    mysql:
        image: mysql:8
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: secret
        volumes:
            - mysql:/var/lib/mysql
        cap_add:
            - SYS_NICE # CAP_SYS_NICE https://stackoverflow.com/a/55706057
        ports:
            - '3306:3306'

volumes:
    mysql:
